openapi: 3.0.3
info:
  title: Pagination Schema
  version: v1
paths: {}
components:
  schemas:
    PaginatedArray:
      type: object
      description: |-
        An array of result elements.
      properties:
        count:
          type: integer
          description: |-
            The number of elements in the returned result.
            Less than or equal to limit.
          example: 25
        offset:
          type: integer
          description: |-
            The index of the first returned element within the collection of all result elements.
          example: 513
        limit:
          type: integer
          description: |-
            The result size limit specified in the request.
          default: 25
          example: 35
        total:
          type: integer
          description: |-
            The total number of elements in the result (not only the results contained in the items).
          example: 1337
