openapi: 3.0.3
info:
  title: Pagination Schema
  version: v1
paths: {}
components:
  headers:
    Pagination-Count:
      description: |-
        The number of elements in the returned result.
        Less than or equal to Pagination-Limit.
      schema:
        type: integer
        example: 25
      required: true
    Pagination-Offset:
      description: |-
        The index of the first returned element within the collection of all result elements.
      schema:
        type: integer
        example: 513
      required: true
    Pagination-Limit:
      description: |-
        The result size limit specified in the request.
      schema:
        type: integer
        default: 25
        example: 35
      required: true
    Pagination-Total:
      description: |-
        The total number of elements in the result (not only the results contained in the items).
      schema:
        type: integer
        example: 1337
      required: true
