package main

import (
	"flag"
	"fmt"
	"math"
	"os"
	"time"

	"codello.dev/ultrastar"
	"codello.dev/ultrastar/txt"
	"github.com/brianvoe/gofakeit/v6"
)

var (
	duet   bool   // generate a duet
	output string // output file
)

func init() {
	flag.Usage = func() {
		_, _ = fmt.Fprintln(flag.CommandLine.Output(), `gensong - Generate Random UltraStar songs

Usage:
  gensong [flags]

Available Flags:`)
		flag.PrintDefaults()
	}
	flag.BoolVar(&duet, "duet", false, "generate a duet instead of a solo song")
	flag.StringVar(&output, "output", "", "write the generated song to this file. By default songs are written to stdout.")
	flag.Parse()
}

func main() {
	song := ultrastar.Song{}
	song.Title = gofakeit.BookTitle()
	song.Artist = gofakeit.BookAuthor()
	song.Genre = gofakeit.BookGenre()
	song.Edition = ""
	song.Creator = gofakeit.Username()
	song.Language = gofakeit.Language()
	song.Year = gofakeit.Number(1930, 2050)
	song.Comment = "generated by gensong"
	song.BPM = ultrastar.BPM(math.Round(gofakeit.Float64Range(320, 1000)*100) / 100)

	song.Gap = time.Duration(gofakeit.Number(0, 30000)) * time.Millisecond

	song.NotesP1 = genNotes()

	if duet {
		song.DuetSinger2 = gofakeit.Name()
		song.DuetSinger1 = gofakeit.Name()
		song.NotesP2 = genNotes()
	}

	file := os.Stdout
	var err error
	if output != "" {
		if file, err = os.Create(output); err != nil {
			fmt.Printf("Error opening file %s: %s", output, err)
			os.Exit(1)
		}
	}
	_ = txt.WriteSong(file, song)
	if err = file.Close(); err != nil {
		fmt.Printf("Error closing file %s: %s", output, err)
		os.Exit(1)
	}
}

// genNotes generates a random sequence of notes, each note with a random word.
// Line breaks are inserted at random.
func genNotes() ultrastar.Notes {
	ns := make(ultrastar.Notes, 0)
	beat := ultrastar.Beat(gofakeit.Number(0, 1000))
	numLines := gofakeit.Number(5, 20)
	for l := 0; l < numLines; l++ {
		numNotes := gofakeit.Number(4, 8)
		rap := gofakeit.Number(1, 30) == 15
		for n := 0; n < numNotes; n++ {
			beat += ultrastar.Beat(gofakeit.Number(1, 20))
			note := genNote(rap)
			note.Start = beat
			beat += note.Duration
			ns = append(ns, note)
		}
		if l < numLines-1 {
			beat += ultrastar.Beat(gofakeit.Number(1, 20))
			note := ultrastar.Note{
				Type:  ultrastar.NoteTypeLineBreak,
				Start: beat,
			}
			ns = append(ns, note)
		}
	}
	return ns
}

// genNote generates a random note.
func genNote(rap bool) (n ultrastar.Note) {
	if gofakeit.Number(0, 10) == 2 {
		if rap {
			n.Type = ultrastar.NoteTypeGoldenRap
		} else {
			n.Type = ultrastar.NoteTypeGolden
		}
	} else {
		if rap {
			n.Type = ultrastar.NoteTypeRap
		} else {
			n.Type = ultrastar.NoteTypeRegular
		}
	}
	n.Duration = ultrastar.Beat(gofakeit.Number(1, 12))
	n.Pitch = ultrastar.Pitch(gofakeit.Number(0, 16))
	n.Text = gofakeit.Word()
	return
}
