openapi: 3.0.3
info:
  title: Pagination Schema
  version: v1


paths: {}


components:
  parameters:
    limit:
      in: query
      name: limit
      required: false
      allowEmptyValue: false
      description: |-
        The limit sets the number of items to return (if available).
        The actual number of results depends on the number of available items.
        Depending on the endpoint the actual maximum limit may be higher or lower.
        
        `limit=0` will always return an empty list.
        This can be useful to find the total number of items.
      schema:
        type: integer
        default: 25
        minimum: 0
        maximum: 100
        example: 50

    offset:
      in: query
      name: offset
      required: false
      allowEmptyValue: false
      description: |-
        The offset specifies the start value for pagination.
        If a previous request has yielded the first 50 items you can use `offset=50&limit=50` to get the next 50 items.
      schema:
        type: integer
        default: 0
        minimum: 0
        example: 25


  headers:
    Pagination-Count:
      description: |-
        The number of elements in the returned result.
        Less than or equal to Pagination-Limit.
      schema:
        type: integer
        example: 25
      required: true

    Pagination-Offset:
      description: |-
        The index of the first returned element within the collection of all result elements.
      schema:
        type: integer
        example: 513
      required: true

    Pagination-Limit:
      description: |-
        The result size limit specified in the request.
      schema:
        type: integer
        default: 25
        example: 35
      required: true

    Pagination-Total:
      description: |-
        The total number of elements in the result (not only the results contained in the items).
      schema:
        type: integer
        example: 1337
      required: true
