openapi: 3.0.3
info:
  title: Error Schemas
  version: 0.1.0
paths: {}
components:
  schemas:
    ProblemDetails:
      description: >-
        A problem details object as specified in
        [RFC 7807](https://www.rfc-editor.org/rfc/rfc7807).
      type: object
      properties:
        type:
          type: string
          format: uri
          description: >-
            URI identifying the problem type. If absent it should be assumed to
            be "about:blank".
          default: "about:blank"
          # TODO: Use actual domain here
          example: "codello.dev/karman/problems/song-not-found"
        title:
          type: string
          description: >-
            A short human-readable summary of the problem. Might be localized.
          example: "Song not found"
        status:
          type: integer
          description: >-
            The status code of the error. Equal to the HTTP response status code.
          example: 404
        detail:
          type: string
          description: >-
            A human readable explanation specific to this occurrence of the
            problem.
          example: >-
            The requested song was not found or you don't have access to it.
        instance:
          type: string
          format: uri
          description: >-
            A URI reference that identifies the specific occurrence of the
            problem.  It may or may not yield further information if
            dereferenced.
          # TODO: Use actual domain here
          example: "/v1/songs/F0FF838A-33ED-4A2B-9E16-AAA804B9BA88/events/481CF77B-3099-445C-A789-58F997233681"
