name: CI
on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ "*" ]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    permissions:
      contents: read
      pull-requests: read
    uses: codello/.github/.github/workflows/go-lint.yml@v0

  test:
    name: Test
    uses: codello/.github/.github/workflows/go-test.yml@v0
    with:
      test-on: ubuntu-latest,ubuntu-20.04,windows-latest,macos-latest

  build:
    name: Build
    uses: codello/.github/.github/workflows/go-build.yml@v0
    with:
      packages: ./cmd/karman
      platforms: linux/amd64,linux/arm64,linux/arm,linux/386
      ldflags: -w -s -X "main.Version=${{ github.ref_type == 'tag' && github.ref_name || '' }}"

  publish:
    name: Publish
    if: ${{ github.event_name == 'push' }}
    needs: [ test, build ]
    permissions:
      contents: read
      packages: write
    uses: codello/.github/.github/workflows/docker-publish.yml@v0
    with:
      image: ${{ github.repository_owner }}/server
      platforms: linux/amd64,linux/arm64,linux/arm,linux/386
